spring:
  profiles:
    default: local

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:monitor;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/distribution
    username: manager
    password: manager

  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

management:
  endpoint:
    health:
      show-details: always
